# Generated by Django 4.0.3 on 2022-03-21 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_custom_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='last_name',
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(blank=True, max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('post_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
