# Generated by Django 4.0.3 on 2022-07-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_info_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30)),
                ('pic', models.ImageField(upload_to='slider_pics')),
                ('state', models.CharField(max_length=7)),
                ('data_slide_to', models.IntegerField()),
            ],
        ),
    ]
