# Generated by Django 4.0.3 on 2022-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_name', models.CharField(max_length=25)),
                ('category', models.ManyToManyField(to='products.category')),
            ],
        ),
    ]
