# Generated by Django 4.0.3 on 2022-03-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_attributes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='category',
        ),
    ]
