# Generated by Django 4.0.3 on 2022-03-26 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_attributes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=25)),
                ('att', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.attributes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
