# Generated by Django 4.0.3 on 2022-03-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
