# Generated by Django 4.0.3 on 2022-03-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 : low'), (2, '2 :medium'), (3, '3 :medium'), (4, '4 :high'), (5, '5 :hgih')], default=0),
        ),
    ]
