# Generated by Django 4.0.3 on 2022-04-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_comment_unknown_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='unknown_user',
            field=models.BooleanField(default=False),
        ),
    ]
