# Generated by Django 4.0.3 on 2022-04-13 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_alter_product_category_delete_category_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_category_name', models.CharField(max_length=15)),
                ('total_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
