# Generated by Django 4.0.3 on 2022-04-13 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_remove_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.category_item'),
            preserve_default=False,
        ),
    ]
