# Generated by Django 4.0.3 on 2022-06-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
    ]
