# Generated by Django 4.0.3 on 2022-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_order_items_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='qunatity',
            field=models.IntegerField(default=0),
        ),
    ]
