# Generated by Django 4.0.3 on 2022-07-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_delivery_alter_order_items_qunatity_order_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='total_number',
        ),
        migrations.AddField(
            model_name='color_value',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
