# Generated by Django 4.0.3 on 2022-07-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0036_reply_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pic',
        ),
    ]
