# Generated by Django 4.0.3 on 2022-08-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_alter_order_delivery_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='days',
            field=models.CharField(default='2', max_length=4),
        ),
    ]
